# Generated by Django 4.2.17 on 2025-04-26 09:09

import data_connector.mixins
import data_connector.submodules.base_content_objects.mixins
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок выведения')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('is_publish', models.BooleanField(default=True, verbose_name='Публиковать?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_allow_view', models.BooleanField(default=True, verbose_name='Разрешить просмотр')),
                ('is_allow_edit', models.BooleanField(default=False, verbose_name='Разрешить редактирование')),
                ('is_allow_delete', models.BooleanField(default=False, verbose_name='Разрешить удаление')),
                ('is_allow_create', models.BooleanField(default=False, verbose_name='Разрешить создание')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип контента')),
            ],
            options={
                'verbose_name': 'Сериализатор',
                'verbose_name_plural': 'Сериализаторы',
            },
            bases=(data_connector.submodules.base_content_objects.mixins.StrVerboseNameMixin, models.Model, data_connector.submodules.base_content_objects.mixins.SlugMixin, data_connector.mixins.DataConnectorMixin, data_connector.submodules.base_content_objects.mixins.AdminChangeButtonMixin, data_connector.submodules.base_content_objects.mixins.AppMixin),
            managers=[
                ('publish', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ForInKeyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(default='default_value', max_length=255, verbose_name='Название')),
                ('integer_field', models.IntegerField(default=0, verbose_name='Целое число')),
                ('float_field', models.FloatField(default=0.0, verbose_name='Число с плавающей точкой')),
                ('boolean_field', models.BooleanField(default=False, verbose_name='Булево значение')),
                ('datetime_field', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('text_field', models.TextField(default='default_value', verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Модель с внешним ключом',
                'verbose_name_plural': 'Модели с внешними ключами',
            },
        ),
        migrations.CreateModel(
            name='ManyToManyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(default='default_value', max_length=255, verbose_name='Название')),
                ('integer_field', models.IntegerField(default=0, verbose_name='Целое число')),
                ('float_field', models.FloatField(default=0.0, verbose_name='Число с плавающей точкой')),
                ('boolean_field', models.BooleanField(default=False, verbose_name='Булево значение')),
                ('datetime_field', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('text_field', models.TextField(default='default_value', verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Модель с множественной связью',
                'verbose_name_plural': 'Модели с множественными связями',
            },
        ),
        migrations.CreateModel(
            name='OneToOneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(default='default_value', max_length=255, verbose_name='Название')),
                ('integer_field', models.IntegerField(default=0, verbose_name='Целое число')),
                ('float_field', models.FloatField(default=0.0, verbose_name='Число с плавающей точкой')),
                ('boolean_field', models.BooleanField(default=False, verbose_name='Булево значение')),
                ('datetime_field', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('text_field', models.TextField(default='default_value', verbose_name='Текст')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RemoteSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Удалённый сайт',
                'verbose_name_plural': 'Удалённые сайты',
            },
        ),
        migrations.CreateModel(
            name='Transmitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('action', models.CharField(choices=[('send', 'Передать'), ('receive', 'Получить')], default='receive', max_length=255, verbose_name='Действие')),
                ('mod', models.CharField(choices=[('test', 'Тестирование'), ('ordinary', 'Обычный')], default='ordinary', max_length=255, verbose_name='Режим')),
                ('model_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID модели')),
                ('filter', models.JSONField(blank=True, default=dict, verbose_name='Фильтр(kwargs)')),
                ('run_on_save', models.BooleanField(default=False, verbose_name='Запустить при сохранении')),
                ('remote_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_connector.remotesite', verbose_name='Удалённый сайт')),
                ('serializer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_connector.dataconnector', verbose_name='Сериализатор')),
            ],
            options={
                'verbose_name': 'Передатчик',
                'verbose_name_plural': 'Передатчики',
            },
        ),
        migrations.CreateModel(
            name='TransmitterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('pending', 'В ожидании'), ('success', 'Успешно'), ('failure', 'Ошибка')], default='new', max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('result', models.JSONField(blank=True, null=True, verbose_name='Результат')),
                ('transmitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_connector.transmitter', verbose_name='Трансмиттер')),
            ],
            options={
                'verbose_name': 'Лог передачи',
                'verbose_name_plural': 'Логи передач',
            },
        ),
        migrations.CreateModel(
            name='SerializerField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('verbose_name', models.CharField(max_length=255, verbose_name='Человекочитаемое название')),
                ('type_for_handler', models.CharField(blank=True, choices=[('AutoField', 'AutoField'), ('CharField', 'CharField'), ('TextField', 'TextField'), ('SlugField', 'SlugField'), ('EmailField', 'EmailField'), ('IntegerField', 'IntegerField'), ('PositiveIntegerField', 'PositiveIntegerField'), ('FloatField', 'FloatField'), ('DecimalField', 'DecimalField'), ('BooleanField', 'BooleanField'), ('DateField', 'DateField'), ('TimeField', 'TimeField'), ('DateTimeField', 'DateTimeField'), ('SlugField', 'SlugField'), ('URLField', 'URLField'), ('JSONField', 'JSONField'), ('FileField', 'FileField'), ('ForeignKey', 'ForeignKey'), ('ManyToManyField', 'ManyToManyField'), ('ManyToOneRel', 'ManyToOneRel'), ('OneToOneField', 'OneToOneField'), ('GenericRelation', 'GenericRelation'), ('GenericForeignKey', 'GenericForeignKey'), ('serializer', 'serializer'), ('cargo_calc__route', 'cargo_calc__route'), ('cargo_calc__services', 'cargo_calc__services'), ('cargo_calc__prices', 'cargo_calc__prices')], max_length=255, null=True, verbose_name='Тип для обработчика')),
                ('type_for_form_handler', models.CharField(blank=True, choices=[('AutoField', 'AutoField'), ('CharField', 'CharField'), ('TextField', 'TextField'), ('SlugField', 'SlugField'), ('EmailField', 'EmailField'), ('IntegerField', 'IntegerField'), ('PositiveIntegerField', 'PositiveIntegerField'), ('FloatField', 'FloatField'), ('DecimalField', 'DecimalField'), ('BooleanField', 'BooleanField'), ('DateField', 'DateField'), ('TimeField', 'TimeField'), ('DateTimeField', 'DateTimeField'), ('SlugField', 'SlugField'), ('URLField', 'URLField'), ('JSONField', 'JSONField'), ('FileField', 'FileField'), ('ForeignKey', 'ForeignKey'), ('ManyToManyField', 'ManyToManyField'), ('ManyToOneRel', 'ManyToOneRel'), ('OneToOneField', 'OneToOneField'), ('GenericRelation', 'GenericRelation'), ('GenericForeignKey', 'GenericForeignKey'), ('serializer', 'serializer'), ('cargo_calc__route', 'cargo_calc__route'), ('cargo_calc__services', 'cargo_calc__services'), ('cargo_calc__prices', 'cargo_calc__prices')], max_length=255, null=True, verbose_name='Тип для обработчика формы')),
                ('incoming_handler', models.CharField(blank=True, choices=[('AutoField', 'AutoField'), ('CharField', 'CharField'), ('TextField', 'TextField'), ('SlugField', 'SlugField'), ('EmailField', 'EmailField'), ('IntegerField', 'IntegerField'), ('PositiveIntegerField', 'PositiveIntegerField'), ('FloatField', 'FloatField'), ('DecimalField', 'DecimalField'), ('BooleanField', 'BooleanField'), ('DateField', 'DateField'), ('TimeField', 'TimeField'), ('DateTimeField', 'DateTimeField'), ('SlugField', 'SlugField'), ('URLField', 'URLField'), ('JSONField', 'JSONField'), ('FileField', 'FileField'), ('ForeignKey', 'ForeignKey'), ('ManyToManyField', 'ManyToManyField'), ('ManyToOneRel', 'ManyToOneRel'), ('OneToOneField', 'OneToOneField'), ('GenericRelation', 'GenericRelation'), ('GenericForeignKey', 'GenericForeignKey'), ('serializer', 'serializer'), ('cargo_calc__route', 'cargo_calc__route'), ('cargo_calc__services', 'cargo_calc__services'), ('cargo_calc__prices', 'cargo_calc__prices')], max_length=255, null=True, verbose_name='Тип для обработчика входящих данных')),
                ('alt_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Альтернативный ключ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('type', models.CharField(choices=[('AutoField', 'AutoField'), ('CharField', 'CharField'), ('TextField', 'TextField'), ('SlugField', 'SlugField'), ('EmailField', 'EmailField'), ('IntegerField', 'IntegerField'), ('PositiveIntegerField', 'PositiveIntegerField'), ('FloatField', 'FloatField'), ('DecimalField', 'DecimalField'), ('BooleanField', 'BooleanField'), ('DateField', 'DateField'), ('TimeField', 'TimeField'), ('DateTimeField', 'DateTimeField'), ('SlugField', 'SlugField'), ('URLField', 'URLField'), ('JSONField', 'JSONField'), ('FileField', 'FileField'), ('ForeignKey', 'ForeignKey'), ('ManyToManyField', 'ManyToManyField'), ('ManyToOneRel', 'ManyToOneRel'), ('OneToOneField', 'OneToOneField'), ('GenericRelation', 'GenericRelation'), ('GenericForeignKey', 'GenericForeignKey'), ('serializer', 'serializer'), ('cargo_calc__route', 'cargo_calc__route'), ('cargo_calc__services', 'cargo_calc__services'), ('cargo_calc__prices', 'cargo_calc__prices')], default='AutoField', max_length=255, verbose_name='Тип')),
                ('data_connector', models.ForeignKey(blank=True, help_text='Сериализатор, к которому относится это поле. Определяет контекст и правила обработки данных.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serializer_fields', to='data_connector.dataconnector', verbose_name='Сериализатор')),
                ('serializer', models.ForeignKey(blank=True, help_text='Сериализатор для обработки связанных данных. Используется для вложенных объектов и связей.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_serializer_fields', to='data_connector.dataconnector', verbose_name='Вложенный сериализатор')),
            ],
            options={
                'verbose_name': 'Поле сериализатора',
                'verbose_name_plural': 'Поля сериализатора',
            },
            bases=(data_connector.mixins.SerializerFieldMixin, data_connector.submodules.base_content_objects.mixins.StrVerboseNameMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MainTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(default='default_value', max_length=255, verbose_name='Название')),
                ('integer_field', models.IntegerField(default=0, verbose_name='Целое число')),
                ('float_field', models.FloatField(default=0.0, verbose_name='Число с плавающей точкой')),
                ('boolean_field', models.BooleanField(default=False, verbose_name='Булево значение')),
                ('datetime_field', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('text_field', models.TextField(default='default_value', verbose_name='Текст')),
                ('for_in_key_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_models', to='data_connector.forinkeymodel')),
                ('many_to_many_models', models.ManyToManyField(blank=True, related_name='main_models', to='data_connector.manytomanymodel')),
                ('one_to_one_model', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_models', to='data_connector.onetoonemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenericRelatedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип контента')),
            ],
            options={
                'verbose_name': 'Модель с общей связью',
                'verbose_name_plural': 'Модели с общими связями',
            },
        ),
    ]
