# Generated by Django 4.2.17 on 2025-04-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_connector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serializerfield',
            name='real_field_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Реальное название поля'),
        ),
        migrations.AlterField(
            model_name='serializerfield',
            name='alt_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Альтернативный ключ(под этим ключом будут возвращены данные)'),
        ),
    ]
