# Generated by Django 4.2.17 on 2025-04-30 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_connector', '0002_serializerfield_real_field_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serializerfield',
            name='real_field_name',
        ),
    ]
