# Generated by Django 4.2.17 on 2025-05-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_connector', '0003_remove_serializerfield_real_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='serializerfield',
            name='field_name_for_method',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название поля для обработки входящих данных'),
        ),
        migrations.AddField(
            model_name='serializerfield',
            name='incoming_method',
            field=models.CharField(blank=True, choices=[('get', 'Найти'), ('create', 'Создать'), ('get_or_create', 'Найти или создать')], max_length=255, null=True, verbose_name='Cпособ обработки входящих данных'),
        ),
    ]
