# Generated by Django 4.2.17 on 2025-05-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_connector', '0005_alter_serializerfield_incoming_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='serializerfield',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
    ]
