# Generated by Django 4.2.17 on 2025-05-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_connector', '0006_serializerfield_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serializerfield',
            name='incoming_method',
            field=models.CharField(choices=[('get', 'Найти'), ('create', 'Создать'), ('get_or_create', 'Найти или создать'), ('get_and_update_or_create', 'Найти и обновить или создать')], default='get', max_length=255, verbose_name='Cпособ обработки входящих данных'),
        ),
    ]
