# Generated by Django 4.2.17 on 2025-05-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_connector', '0007_alter_serializerfield_incoming_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='serializerfield',
            name='data_type',
            field=models.CharField(choices=[('rest', 'REST'), ('form', 'FORM')], default='rest', max_length=255, verbose_name='Тип данных'),
        ),
    ]
