# Generated by Django 4.2.17 on 2025-06-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_connector', '0008_serializerfield_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serializerfield',
            name='data_type',
            field=models.CharField(choices=[('rest', 'REST'), ('form', 'FORM'), ('key-form', 'KEY-FORM')], default='rest', max_length=255, verbose_name='Тип данных'),
        ),
    ]
