# Generated by Django 4.2.17 on 2025-06-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_connector', '0009_alter_serializerfield_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='serializerfield',
            name='real_field_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Реальное название поля'),
        ),
    ]
