# Generated by Django 4.2.17 on 2025-06-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_connector', '0012_alter_serializerfield_incoming_handler_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serializerfield',
            name='incoming_handler',
            field=models.CharField(blank=True, choices=[('AutoField', 'AutoField'), ('CharField', 'CharField'), ('TextField', 'TextField'), ('SlugField', 'SlugField'), ('EmailField', 'EmailField'), ('IntegerField', 'IntegerField'), ('PositiveIntegerField', 'PositiveIntegerField'), ('FloatField', 'FloatField'), ('DecimalField', 'DecimalField'), ('BooleanField', 'BooleanField'), ('DateField', 'DateField'), ('TimeField', 'TimeField'), ('DateTimeField', 'DateTimeField'), ('SlugField', 'SlugField'), ('URLField', 'URLField'), ('JSONField', 'JSONField'), ('FileField', 'FileField'), ('ForeignKey', 'ForeignKey'), ('ManyToManyField', 'ManyToManyField'), ('PseudoManyToManyField', 'PseudoManyToManyField'), ('ManyToOneRel', 'ManyToOneRel'), ('OneToOneField', 'OneToOneField'), ('GenericRelation', 'GenericRelation'), ('GenericForeignKey', 'GenericForeignKey'), ('serializer', 'serializer'), ('cargo_calc__route', 'cargo_calc__route'), ('cargo_calc__tranzit_route', 'cargo_calc__transit_route'), ('cargo_calc__services', 'cargo_calc__services'), ('cargo_calc__prices', 'cargo_calc__prices')], max_length=255, null=True, verbose_name='Тип для обработчика входящих данных'),
        ),
        migrations.AlterField(
            model_name='serializerfield',
            name='type',
            field=models.CharField(choices=[('AutoField', 'AutoField'), ('CharField', 'CharField'), ('TextField', 'TextField'), ('SlugField', 'SlugField'), ('EmailField', 'EmailField'), ('IntegerField', 'IntegerField'), ('PositiveIntegerField', 'PositiveIntegerField'), ('FloatField', 'FloatField'), ('DecimalField', 'DecimalField'), ('BooleanField', 'BooleanField'), ('DateField', 'DateField'), ('TimeField', 'TimeField'), ('DateTimeField', 'DateTimeField'), ('SlugField', 'SlugField'), ('URLField', 'URLField'), ('JSONField', 'JSONField'), ('FileField', 'FileField'), ('ForeignKey', 'ForeignKey'), ('ManyToManyField', 'ManyToManyField'), ('PseudoManyToManyField', 'PseudoManyToManyField'), ('ManyToOneRel', 'ManyToOneRel'), ('OneToOneField', 'OneToOneField'), ('GenericRelation', 'GenericRelation'), ('GenericForeignKey', 'GenericForeignKey'), ('serializer', 'serializer'), ('cargo_calc__route', 'cargo_calc__route'), ('cargo_calc__tranzit_route', 'cargo_calc__transit_route'), ('cargo_calc__services', 'cargo_calc__services'), ('cargo_calc__prices', 'cargo_calc__prices')], default='AutoField', max_length=255, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='serializerfield',
            name='type_for_form_handler',
            field=models.CharField(blank=True, choices=[('AutoField', 'AutoField'), ('CharField', 'CharField'), ('TextField', 'TextField'), ('SlugField', 'SlugField'), ('EmailField', 'EmailField'), ('IntegerField', 'IntegerField'), ('PositiveIntegerField', 'PositiveIntegerField'), ('FloatField', 'FloatField'), ('DecimalField', 'DecimalField'), ('BooleanField', 'BooleanField'), ('DateField', 'DateField'), ('TimeField', 'TimeField'), ('DateTimeField', 'DateTimeField'), ('SlugField', 'SlugField'), ('URLField', 'URLField'), ('JSONField', 'JSONField'), ('FileField', 'FileField'), ('ForeignKey', 'ForeignKey'), ('ManyToManyField', 'ManyToManyField'), ('PseudoManyToManyField', 'PseudoManyToManyField'), ('ManyToOneRel', 'ManyToOneRel'), ('OneToOneField', 'OneToOneField'), ('GenericRelation', 'GenericRelation'), ('GenericForeignKey', 'GenericForeignKey'), ('serializer', 'serializer'), ('cargo_calc__route', 'cargo_calc__route'), ('cargo_calc__tranzit_route', 'cargo_calc__transit_route'), ('cargo_calc__services', 'cargo_calc__services'), ('cargo_calc__prices', 'cargo_calc__prices')], max_length=255, null=True, verbose_name='Тип для обработчика формы'),
        ),
        migrations.AlterField(
            model_name='serializerfield',
            name='type_for_handler',
            field=models.CharField(blank=True, choices=[('AutoField', 'AutoField'), ('CharField', 'CharField'), ('TextField', 'TextField'), ('SlugField', 'SlugField'), ('EmailField', 'EmailField'), ('IntegerField', 'IntegerField'), ('PositiveIntegerField', 'PositiveIntegerField'), ('FloatField', 'FloatField'), ('DecimalField', 'DecimalField'), ('BooleanField', 'BooleanField'), ('DateField', 'DateField'), ('TimeField', 'TimeField'), ('DateTimeField', 'DateTimeField'), ('SlugField', 'SlugField'), ('URLField', 'URLField'), ('JSONField', 'JSONField'), ('FileField', 'FileField'), ('ForeignKey', 'ForeignKey'), ('ManyToManyField', 'ManyToManyField'), ('PseudoManyToManyField', 'PseudoManyToManyField'), ('ManyToOneRel', 'ManyToOneRel'), ('OneToOneField', 'OneToOneField'), ('GenericRelation', 'GenericRelation'), ('GenericForeignKey', 'GenericForeignKey'), ('serializer', 'serializer'), ('cargo_calc__route', 'cargo_calc__route'), ('cargo_calc__tranzit_route', 'cargo_calc__transit_route'), ('cargo_calc__services', 'cargo_calc__services'), ('cargo_calc__prices', 'cargo_calc__prices')], max_length=255, null=True, verbose_name='Тип для обработчика'),
        ),
    ]
