# Generated by Django 4.2.17 on 2025-06-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_connector', '0014_alter_serializerfield_incoming_handler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serializerfield',
            name='is_key_field',
            field=models.BooleanField(default=False, verbose_name='Является ключевым полем'),
        ),
    ]
