# Generated by Django 4.2.17 on 2025-06-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_connector', '0015_serializerfield_is_key_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='serializerfield',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='Обязательное поле'),
        ),
    ]