# Generated by Django 4.2.17 on 2025-10-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_connector', '0018_alter_serializerfield_incoming_handler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serializerfield',
            name='default_object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID обьекта по умолчанию(⚠ Проверьте существует ли обьект)'),
        ),
    ]
