from django.core.management.base import BaseCommand


class Command(BaseCommand):
    help = 'Показывает примеры использования системы дампов'

    def handle(self, *args, **options):
        self.stdout.write('=' * 80)
        self.stdout.write('ПРИМЕРЫ ИСПОЛЬЗОВАНИЯ СИСТЕМЫ ДАМПОВ')
        self.stdout.write('=' * 80)
        
        self.stdout.write('\n📋 Сценарий 1: Локальная разработка')
        self.stdout.write('-' * 50)
        self.stdout.write('1. Создайте тестовые данные:')
        self.stdout.write('   python manage.py create_test_dump')
        self.stdout.write('\n2. Создайте дамп (с прогресс-барами):')
        self.stdout.write('   python manage.py create_dump --output /path/to/my_dump.json')
        self.stdout.write('\n3. Сохраните файл my_dump.json в репозитории')
        self.stdout.write('\n4. На другой машине загрузите дамп:')
        self.stdout.write('   python manage.py load_dump /path/to/my_dump.json --clear')
        
        self.stdout.write('\n📋 Сценарий 2: Миграция данных между средами')
        self.stdout.write('-' * 50)
        self.stdout.write('1. На продакшене создайте дамп:')
        self.stdout.write('   python manage.py create_dump --output /backups/production_data.json')
        self.stdout.write('\n2. Скопируйте файл на staging:')
        self.stdout.write('   scp /backups/production_data.json staging:/path/to/project/')
        self.stdout.write('\n3. На staging загрузите дамп:')
        self.stdout.write('   python manage.py load_dump /path/to/project/production_data.json --clear')
        
        self.stdout.write('\n📋 Сценарий 3: Частичная миграция')
        self.stdout.write('-' * 50)
        self.stdout.write('1. Создайте дамп только нужных моделей:')
        self.stdout.write('   python manage.py create_dump --models dataconnector serializerfield --output /config/config_data.json')
        self.stdout.write('\n2. Загрузите только эти модели:')
        self.stdout.write('   python manage.py load_dump /config/config_data.json --models dataconnector serializerfield')
        
        self.stdout.write('\n📋 Сценарий 4: Тестирование системы')
        self.stdout.write('-' * 50)
        self.stdout.write('1. Запустите полное тестирование:')
        self.stdout.write('   python manage.py test_dump_system')
        self.stdout.write('\n2. Или с сохранением данных:')
        self.stdout.write('   python manage.py test_dump_system --keep-data')
        
        self.stdout.write('\n📋 Сценарий 5: Резервное копирование')
        self.stdout.write('-' * 50)
        self.stdout.write('1. Создайте дамп с временной меткой:')
        self.stdout.write('   python manage.py create_dump --output /backups/backup_$(date +%Y%m%d_%H%M%S).json')
        self.stdout.write('\n2. Или создайте дамп с исключением логов:')
        self.stdout.write('   python manage.py create_dump --exclude transmitterlog --output /backups/clean_backup.json')
        
        self.stdout.write('\n📋 Сценарий 6: Автоматическое создание дампов')
        self.stdout.write('-' * 50)
        self.stdout.write('1. Создайте дамп в папку по умолчанию (без --output):')
        self.stdout.write('   python manage.py create_dump')
        self.stdout.write('   # Файл будет создан в: BASE_DIR/fixtures/dumps/data_connector_dump_YYYYMMDD_HHMMSS.json')
        self.stdout.write('\n2. Создайте дамп в относительном пути:')
        self.stdout.write('   python manage.py create_dump --output ./my_dumps/latest.json')
        self.stdout.write('\n3. Создайте дамп в абсолютном пути:')
        self.stdout.write('   python manage.py create_dump --output /home/user/backups/data_connector.json')
        
        self.stdout.write('\n🔧 Полезные команды')
        self.stdout.write('-' * 50)
        self.stdout.write('• Просмотр доступных команд:')
        self.stdout.write('  python manage.py help | grep dump')
        self.stdout.write('\n• Создание дампа с подробным выводом:')
        self.stdout.write('  python manage.py create_dump --verbosity=2')
        self.stdout.write('\n• Загрузка дампа с проверкой:')
        self.stdout.write('  python manage.py load_dump my_dump.json --verbosity=2')
        
        self.stdout.write('\n📊 Прогресс-бары')
        self.stdout.write('-' * 50)
        self.stdout.write('• Система автоматически показывает прогресс обработки:')
        self.stdout.write('  - Общий прогресс по моделям')
        self.stdout.write('  - Прогресс обработки объектов каждой модели')
        self.stdout.write('  - Информация о количестве обработанных объектов')
        self.stdout.write('\n• Пример вывода:')
        self.stdout.write('  Обработка моделей: 100%|██████████| 5/5 [00:02<00:00,  2.1модель/с]')
        self.stdout.write('    dataconnector: 100%|██████████| 10/10 [00:01<00:00,  8.2объект/с]')
        
        self.stdout.write('\n⚠️  Важные замечания')
        self.stdout.write('-' * 50)
        self.stdout.write('• Всегда делайте резервную копию перед загрузкой дампа')
        self.stdout.write('• Используйте --clear только когда уверены в замене данных')
        self.stdout.write('• Generic relations корректно обрабатываются автоматически')
        self.stdout.write('• Файлы дампов по умолчанию сохраняются в BASE_DIR/fixtures/dumps/')
        self.stdout.write('• Система поддерживает все типы полей Django')
        self.stdout.write('• Прогресс-бары работают только в интерактивном режиме')
        self.stdout.write('• При указании --output система автоматически создаст нужные директории')
        
        self.stdout.write('\n📁 Структура файлов')
        self.stdout.write('-' * 50)
        self.stdout.write('BASE_DIR/')
        self.stdout.write('├── fixtures/')
        self.stdout.write('│   └── dumps/                    # Место по умолчанию для дампов')
        self.stdout.write('│       ├── data_connector_dump_20241201_143022.json')
        self.stdout.write('│       └── auto_generated_dumps.json')
        self.stdout.write('├── my_dumps/                     # Пользовательские папки')
        self.stdout.write('│   └── latest.json')
        self.stdout.write('└── data_connector/')
        self.stdout.write('    ├── management/')
        self.stdout.write('    │   └── commands/')
        self.stdout.write('    │       ├── create_dump.py          # Создание дампа')
        self.stdout.write('    │       ├── load_dump.py            # Загрузка дампа')
        self.stdout.write('    │       ├── create_test_dump.py     # Тестовые данные')
        self.stdout.write('    │       ├── test_dump_system.py     # Тестирование')
        self.stdout.write('    │       └── example_usage.py        # Этот файл')
        self.stdout.write('    └── fixtures/')
        self.stdout.write('        └── zayavka.json               # Существующий дамп')
        
        self.stdout.write('\n' + '=' * 80)
        self.stdout.write('Для получения дополнительной информации см. README.md')
        self.stdout.write('=' * 80) 